repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, jupyter]
        exclude: ^src/dara/server/
      - id: ruff-format
        types_or: [python, jupyter]
        exclude: ^src/dara/server/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
        exclude: ^src/dara/server/
      - id: check-symlinks
        exclude: ^src/dara/server/
      - id: check-yaml
        exclude: ^src/dara/server/
      - id: destroyed-symlinks
        exclude: ^src/dara/server/
      - id: end-of-file-fixer
        exclude_types: [jupyter]
        exclude: ^src/dara/server/
      - id: mixed-line-ending
        exclude: ^src/dara/server/
      - id: trailing-whitespace
        exclude: ^src/dara/server/

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        stages: [pre-commit, commit-msg]
        args: [--check-filenames, --skip=*.lock, package-lock.json]
        exclude: ^(src/dara/server/|src/dara/data/)

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.0
    hooks:
      - id: nbstripout
        args: [--drop-empty-cells, --keep-output]
        exclude: ^src/dara/server/
